export default {
    OPEN_DOJO: 'OPEN_DOJO',
    CLOSE_DOJO: 'CLOSE_DOJO',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    SET_USER: 'SET_USER',
    TRYING_TO_LOGIN: 'TRYING_TO_LOGIN',
    TRYING_TO_LOGOUT: 'TRYING_TO_LOGOUT',
    TRYING_TO_REGISTRATION: 'TRYING_TO_REGISTRATION',
    SUCCESS_REGISTRATION: 'SUCCESS_REGISTRATION',
    COULD_NOT_LOGIN: 'COULD_NOT_LOGIN',
    COULD_NOT_LOGOUT: 'COULD_NOT_LOGOUT',
    COULD_NOT_REGISTRATION: 'COULD_NOT_REGISTRATION',
    SERVER_ERROR: 'SERVER_ERROR',
    CLEAR_SERVER_ERROR: 'CLEAR_SERVER_ERROR'
};